### ISSUE TITLE
Update dynamodb index/table

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [SC5/serverless-plugin-additional-stacks#12]
I am trying to update a dynamodb table (index, and/or keys). Is this possible with this library? Do I have to remove the entire stack before doing so?

**Comment by stephan-nordnes-eriksen** [comment]
For reference, I am getting the following errors:

```
Serverless: Updating additional stack permanent...
....
Serverless: Additional stack permanent updated failed (UPDATE_ROLLBACK_COMPLETE).

  Error --------------------------------------------------

  Additional stack permanent updated failed (UPDATE_ROLLBACK_COMPLETE)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Additional stack permanent updated failed (UPDATE_ROLLBACK_COMPLETE)
    at describeStack.then.response (/Users/project/node_modules/serverless-plugin-additional-stacks/index.js:433:35)
From previous event:
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at readMore (/Users/project/node_modules/serverless-plugin-additional-stacks/index.js:415:8)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2
     Serverless Version:     1.27.3

```
